backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "portfolioEntries" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio Entries" # Used in the UI
    folder: "CraigDrone/portfolioEntries" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Type", name: "type", widget: "select", options: ["Real Estate", "Construction", "Golf Courses", "Other", "Events"] }
      - { label: "VideoURL", name: "videoURL", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "services"  
    label: "Services" 
    folder: "CraigDrone/services" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "PictureURL", name: "pictureURL", widget: "string" }
      - { label: "Subtext", name: "subtext", widget: "markdown" }

  - name: "Home" 
    label: "home" 
    folder: "CraigDrone/home" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "MediaURL", name: "mediaURL", widget: "string" }
      - { label: "Subtext", name: "subtext", widget: "string" }